name: CI
on:
    push:
        branches: [ master,dev ]   
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [20.x]    
        environment:  diningProduction 
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
          - name: 'Create env file'
            run: |
              echo "${{ secrets.ENV_FILE }}" > .env
          - run: npm install 
          - run: npm install --prefix frontend
          - run: npm run build --if-present
          - run: npm test
    deploy:
      needs: [test]
      runs-on: ubuntu-latest 
      environment:  diningProduction 
      steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/repo/DiningService
            git pull origin master
            npm install 
            npm install --prefix frontend
            pm2 start npm --name "dining" -- run server  


