name: CI
on:
    push:
        branches: [ master ]   
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [12.x]          
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
          - name: 'Create env file'
            run: |
              echo "${{ secrets.ENV_FILE }}" > .env
          - run: npm install 
          - run: npm install --prefix frontend
          - run: npm run build --if-present
          - run: npm test
